package com.example.ecommerceproject.constant;

public enum Category {
  FASHION_CLOTHING, BEAUTY, BABY,
  FOOD, KITCHEN_SUPPLIES, LIVING_SUPPLIES,
  HOME_INTERIOR, ELECTRONICS_DIGITAL, SPORTS,
  CAR_SUPPLIES, BOOKS_MUSIC_DVD, TOYS_HOBBIES,
  OFFICE_SUPPLIES, PET_SUPPLIES, HEALTH_FOOD
}

